# Default configuration file for the NLP project

project:
  name: NewsTitleClassification
  description: "A project to classify news titles into categories using NLP techniques."
  version: 1.0
  author: "Your Name"

data:
  data_dir: "./dataset"
  train_data_name: "train.txt"
  test_data_name: "test.txt"
  label_dict_name: "label_dict.txt"
  dict_name: "dict.txt"
  validation_split: 0.2
  

model:
  type: "BiLSTM"
  hidden_size: 1024
  embedding_size: 256
  max_seq_len: 64
  n_classes: 14
  n_layers: 3
  dropout_rate: 0.3
  direction: "bidirectional"

training:
  epochs: 20
  batch_size: 64
  learning_rate: 0.001
  optimizer: "adam"
  betas: [0.9, 0.99]
  weight_decay: 0.0001
  loss_function: "cross_entropy"

logging:
  log_dir: "./logs"
  log_level: "INFO"
  save_model: true
  save_model_path: "./models/best_model.pth"

evaluation:
  metrics:
    - "accuracy"
    - "f1_score"
    - "precision"
    - "recall"

parameters_version: "first"